# Generated by Django 5.1.12 on 2026-09-16 03:58

import django.db.models.deletion
import receiving.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=receiving.models.product_catalog_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, db_index=True, max_length=160)),
                ('pon_sku', models.CharField(blank=True, db_index=True, max_length=160)),
                ('customer', models.CharField(blank=True, db_index=True, max_length=80)),
                ('code2', models.CharField(blank=True, db_index=True, max_length=160)),
                ('raw_data', models.JSONField(default=dict)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='receiving.productcatalog')),
            ],
            options={
                'ordering': ['source_row', 'id'],
                'indexes': [models.Index(fields=['catalog', 'code'], name='receiving_p_catalog_e280c3_idx'), models.Index(fields=['catalog', 'pon_sku'], name='receiving_p_catalog_0c0b95_idx'), models.Index(fields=['catalog', 'code2'], name='receiving_p_catalog_90d75f_idx')],
            },
        ),
    ]
