# Generated by Django 5.1.12 on 2026-09-16 04:18

import django.db.models.deletion
import receiving.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_product_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PRODUCT_CHECK', 'Product check and barcodes'), ('NEW_PRODUCT', 'New Product Import')], max_length=20)),
                ('file', models.FileField(upload_to=receiving.models.generated_export_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=30)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exports', to='receiving.container')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('long_code', models.CharField(blank=True, max_length=160)),
                ('short_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=255)),
                ('length_mm', models.PositiveIntegerField()),
                ('height_mm', models.PositiveIntegerField()),
                ('width_mm', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_definitions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_product_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
