# Generated by Django 5.1.15 on 2026-09-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0014_alter_shortnamedictionaryrule_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerproductstatus',
            name='import_classification',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='containerproductstatus',
            name='import_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
