# Generated by Django 5.1.15 on 2026-10-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import receiving.models


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0015_original_import_selection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstScanSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mode", models.CharField(choices=[("AUTO", "Auto"), ("CODE", "Code"), ("LONG_CODE", "Long Code")], default="AUTO", max_length=12)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("PAUSED", "Paused"), ("FINISHED", "Finished")], default="ACTIVE", max_length=12)),
                ("current_pallet", models.CharField(blank=True, max_length=30)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="first_scan_sessions", to="receiving.importbatch")),
                ("container", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="first_scan_sessions", to="receiving.container")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="FirstScanPause",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resumed_at", models.DateTimeField(blank=True, null=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pauses", to="receiving.firstscansession")),
            ],
            options={"ordering": ["started_at", "id"]},
        ),
        migrations.CreateModel(
            name="FirstScanEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("PALLET", "Pallet"), ("BIKE", "Bike")], max_length=10)),
                ("input_type", models.CharField(choices=[("PALLET", "Pallet"), ("CODE", "Code"), ("LONG_CODE", "Long Code")], max_length=12)),
                ("result", models.CharField(choices=[("SUCCESS", "Success"), ("WARNING", "Warning"), ("ERROR", "Error")], max_length=10)),
                ("scanned_value", models.CharField(max_length=180)),
                ("resolved_code", models.CharField(blank=True, max_length=100)),
                ("long_code", models.CharField(blank=True, max_length=160)),
                ("pallet", models.CharField(blank=True, max_length=30)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("scanned_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("normalized_line", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="first_scan_event", to="receiving.normalizedline")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="receiving.firstscansession")),
            ],
            options={"ordering": ["-scanned_at", "-id"]},
        ),
        migrations.CreateModel(
            name="FirstScanPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=receiving.models.first_scan_photo_upload_path)),
                ("pallet", models.CharField(blank=True, max_length=30)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="photos", to="receiving.firstscanevent")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="receiving.firstscansession")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-captured_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="firstscansession",
            constraint=models.UniqueConstraint(condition=models.Q(("status__in", ["ACTIVE", "PAUSED"])), fields=("container",), name="unique_open_first_scan_session_per_container"),
        ),
    ]
