# Generated by Django 5.1.15 on 2026-10-05 21:19

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0016_first_scan_scanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondScanMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(max_length=10)),
                ('expected_product', models.CharField(max_length=100)),
                ('source_location', models.CharField(blank=True, max_length=30)),
                ('wh_loc', models.CharField(blank=True, max_length=30)),
                ('existing_serial', models.CharField(blank=True, max_length=160)),
                ('long_sku', models.CharField(blank=True, max_length=160)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=5)),
                ('movement_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('product_verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_scan_movements', to='receiving.container')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SecondScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(blank=True, max_length=5)),
                ('pending_location', models.CharField(blank=True, max_length=5)),
                ('movement_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('product_verified_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('known_serials', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_scan_session', to='receiving.container')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pending_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receiving.secondscanmovement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='secondscanmovement',
            constraint=models.UniqueConstraint(fields=('container', 'movement'), name='unique_second_scan_container_movement'),
        ),
        migrations.AddConstraint(
            model_name='secondscanmovement',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Right('serial', 16)), condition=models.Q(('serial', ''), _negated=True), name='unique_second_scan_serial'),
        ),
        migrations.AddConstraint(
            model_name='secondscanmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('product_code', ''), ('product_verified_at__isnull', True), ('serial', '')), models.Q(('completed_at__isnull', False), ('movement_scanned_at__isnull', False), ('product_code', models.F('expected_product')), ('product_verified_at__isnull', False), models.Q(('serial', ''), _negated=True), models.Q(('location', ''), _negated=True)), _connector='OR'), name='second_scan_requires_product_validation'),
        ),
    ]
